<div class="admin__fieldset-wrapper-content admin__fieldset">
    <div class="admin__field _required">
        <div class="admin__field-label">
            <label>
                <span><?= __('Notice‌:') ?></span>
            </label>
        </div>
        <div class="admin__field-control">
            <?= __('Please use the right menu bar to add admin menus') ?>
        </div>
    </div>
</div>